version: '3.1'

services:

  bdd:
    container_name: bdd
    image: mariadb:latest
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - "3306"
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: api_docker
      MARIADB_USER: roger
      MARIADB_PASSWORD: regor

  api:
    container_name: api
    image: cocor31/api_docker:main
    restart: always
    expose:
      - "23000"
    environment:
      DB_HOST: bdd
      DB_NAME: api_docker
      DB_USER: roger
      DB_PASS: regor
      SERVER_PORT: 23000
      PREFIX: /api
    depends_on:
      bdd:
        condition: service_started

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    expose:
      - "8080"
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./frontend:/var/www/front-end
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
