name: Deploiement continu sur Server

on:
    workflow_call

jobs:
    push:      
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Docker login
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
            username: ${{ secrets.DOCKERHUB_LOGIN }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Extract Metada
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: cocor31/api_docker

        - name: Build and Push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.label }}
    send_compose:
        needs: [push]
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          # - name: Configure SSH
          #   uses: webfactory/ssh-agent@v0.5.1
          #   with:
          #     ssh-private-key: ${{ secrets.SSH_KEY }}
          - name: copy via ssh key
            uses: appleboy/scp-action@v0.1.4
            with:
              host: ${{ secrets.HOST }}
              username: ${{ secrets.USERNAME }}
              port: ${{ secrets.PORT }}
              key: ${{ secrets.SSH_KEY }}
              source: ${{ secrets.SOURCE_DIR }}
              target: ${{ secrets.TARGET_DIR }}  

              # host: ${{ secrets.HOST }}
              # username: ${{ secrets.HOST_USERNAME }}
              # port: ${{ secrets.PORT }}
              # key: ${{ secrets.SSH_KEY }}

              # source: ${{ secrets.SOURCE_DIR }}
              # target: ${{ secrets.TARGET_DIR }} 

    # pull:
    #   needs: [push,send_compose]
    #   runs-on: ubuntu-latest
      
    #   steps:
    #     - name: Checkout
    #       uses: actions/checkout@v3      
    #     - name: Server update
    #       uses: appleboy/ssh-action@master
    #       with:
    #         host: ${{ secrets.HOST }}
    #         username: ${{ secrets.HOST_USERNAME }}
    #         port: ${{ secrets.PORT }}
    #         key: ${{ secrets.SSH_KEY }}

    #         script: |
    #           docker pull cocor31/api_docker
    #           docker-compose up -d
                
          
 