name: Deploiement continu sur Server

on:
    workflow_call

jobs:
    push:      
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Docker login
          uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
          with:
            username: ${{ secrets.DOCKERHUB_LOGIN }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Extract Metada
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: cocor31/api_docker

        - name: Build and Push
          uses: docker/build-push-action@v4
          with:
            context: .
            file: ./Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.label }}
    send_compose:
        needs: [push]
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: copy via ssh key
            uses: appleboy/scp-action@v0.1.4
            with:
              host: ${{ secrets.SERVER_HOST }}
              username: ${{ secrets.HOST_USERNAME }}
              port: 22
              key: ${{ secrets.SSH_KEY }}
              source: "./docker-compose.yml"
              target: "."  
                
          
 